### DISCUSSION TITLE
home assistant YAML code for MQTT discovery

### DISCUSSION THREAD

**Discussion by Infernoken76** [SBFspot/SBFspot#654] [General]
Hi,

after succesfull setup of MQTT on my Raspberry PI, wanted a good discovery of the device in Home Assistant...

Following code added the entities I defined under a single MQTT device.

Please use and edit as you please...

```
mqtt:
  sensor:
    - name: "Inverter Timestamp"
      unique_id: "inverter_timestamp"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.Timestamp }}"
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Sunrise"
      unique_id: "inverter_sunrise"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.SunRise }}"
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Sunset"
      unique_id: "inverter_sunset"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.SunSet }}"
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Serial"
      unique_id: "inverter_serial"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.InvSerial }}"
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Name"
      unique_id: "inverter_name"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.InvName }}"
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Time"
      unique_id: "inverter_time"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.InvTime }}"
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Status"
      unique_id: "inverter_status"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.InvStatus }}"
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Temperature"
      unique_id: "inverter_temperature"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.InvTemperature }}"
      unit_of_measurement: "°C"
      device_class: temperature
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Grid Relay/Contactor"
      unique_id: "inverter_grid_relay_contactor"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.InvGridRelay }}"
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Today Energy"
      unique_id: "inverter_today_energy"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.EToday }}"
      unit_of_measurement: "kWh"
      icon: mdi:solar-power
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Total Energy"
      unique_id: "inverter_total_energy"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.ETotal }}"
      unit_of_measurement: "kWh"
      icon: mdi:solar-power
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter Instant Power"
      unique_id: "inverter_instant_power"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.PACTot | int }}"
      unit_of_measurement: "W"
      device_class: power
      icon: mdi:solar-power
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter DC Power String 1"
      unique_id: "inverter_dc_power_string_1"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.PDC1 }}"
      unit_of_measurement: "W"
      device_class: power
      icon: mdi:solar-power
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter DC Power String 2"
      unique_id: "inverter_dc_power_string_2"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.PDC2 }}"
      unit_of_measurement: "W"
      device_class: power
      icon: mdi:solar-power
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter DC Voltage String 1"
      unique_id: "inverter_dc_voltage_string_1"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.UDC1 }}"
      unit_of_measurement: "V"
      icon: mdi:solar-power
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter DC Voltage String 2"
      unique_id: "inverter_dc_voltage_string_2"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.UDC2 }}"
      unit_of_measurement: "V"
      icon: mdi:solar-power
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter DC Current String 1"
      unique_id: "inverter_dc_current_string_1"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.IDC1 }}"
      unit_of_measurement: "A"
      icon: mdi:solar-power
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
    - name: "Inverter DC Current String 2"
      unique_id: "inverter_dc_current_string_2"
      state_topic: "sbfspot/123456"
      value_template: "{{ value_json.IDC2 }}"
      unit_of_measurement: "A"
      icon: mdi:solar-power
      device:
        identifiers: "SBFSpot-SB4000"
        manufacturer: "SBFSpot"
        name: "SBFSpot-SB4000"
        model: "V1"
```
